name: IS-Uniformity-Test
dependencies:
  - python=3.9
  - numpy=1.21
  - pandas=1.3
  - matplotlib=3.5
  - pillow=9.3
  - rawpy=0.17.3
  - opencv=4.6
  - notebook=6.5.2
  - pip
  - pip:
      - exiftool==0.5.5